# Generated by Django 3.0.7 on 2020-06-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='component',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='member',
            name='url',
            field=models.URLField(),
        ),
    ]
