# Generated by Django 3.0.7 on 2020-06-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(blank=True, choices=[('alumni', 'Alumni'), ('collaborators', 'Collaborators'), ('contributors', 'Contributors'), ('team', 'Team')], max_length=128),
        ),
    ]
