# Generated by Django 3.0.7 on 2020-06-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_auto_20200621_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='img',
            field=models.ImageField(upload_to='get_involved'),
        ),
    ]
