# Generated by Django 3.0.7 on 2020-06-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_auto_20200621_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
