# Generated by Django 3.0.7 on 2020-06-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
