# Generated by Django 3.0.7 on 2020-06-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0010_announcement_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
