# Generated by Django 3.0.7 on 2020-06-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0011_announcement_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='component',
            field=models.CharField(blank=True, choices=[('nlp', 'NeuroNLP'), ('gfx', 'NeuroGFX'), ('fbl', 'FlyBrainLab'), ('neuroarch', 'NeuroArch'), ('na', 'N/A')], default='na', max_length=128),
        ),
        migrations.AddField(
            model_name='gallery',
            name='species',
            field=models.CharField(blank=True, choices=[('adult', 'Adult'), ('larva', 'Larva'), ('na', 'N/A')], default='na', max_length=128),
        ),
    ]
