# Generated by Django 3.0.7 on 2020-06-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0013_gallery_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='tag_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
