# Generated by Django 3.0.7 on 2020-06-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0014_gallery_tag_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrainMaps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('subtitle', models.CharField(max_length=512)),
                ('img', models.ImageField(upload_to='')),
                ('desc', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
    ]
