# Generated by Django 3.0.7 on 2020-07-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0015_brainmaps'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videofile', models.FileField(upload_to='')),
            ],
        ),
    ]
