# Generated by Django 3.0.7 on 2020-07-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0016_frontpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontpage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
