# Generated by Django 3.0.7 on 2020-07-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0017_frontpage_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontpage',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
