# Generated by Django 3.0.7 on 2020-07-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0018_frontpage_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontPageCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('subtitle', models.CharField(max_length=2048)),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('url', models.URLField(help_text='url to a nother website', null=True)),
                ('link', models.URLField(help_text='rounterLink on the angular page', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='FrontPage',
            new_name='FrontPageVideo',
        ),
    ]
