# Generated by Django 3.0.7 on 2020-07-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0019_auto_20200706_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontpagecard',
            name='link',
            field=models.URLField(blank=True, help_text='rounterLink on the angular page'),
        ),
        migrations.AlterField(
            model_name='frontpagecard',
            name='url',
            field=models.URLField(blank=True, help_text='url to a nother website'),
        ),
    ]
