# Generated by Django 3.0.7 on 2020-07-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0021_auto_20200706_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontpagecard',
            name='order',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
