# Generated by Django 3.0.7 on 2020-07-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0022_frontpagecard_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontpagecard',
            name='subtitle',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
