# Generated by Django 3.0.7 on 2020-07-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0023_auto_20200707_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontpagevideo',
            name='imagefile',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
