# Generated by Django 3.0.7 on 2020-07-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0025_pageheader'),
    ]

    operations = [
        migrations.AddField(
            model_name='brainmaps',
            name='info_url',
            field=models.URLField(blank=True),
        ),
    ]
