# Generated by Django 3.0.7 on 2021-02-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0026_brainmaps_info_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('img', models.ImageField(upload_to='')),
                ('desc', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
