# Generated by Django 3.0.7 on 2021-02-14 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0027_genericimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GenericImages',
            new_name='GenericImage',
        ),
    ]
