# Generated by Django 3.1.6 on 2021-02-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0028_auto_20210214_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='brainmaps',
            name='category',
            field=models.CharField(choices=[('connectome', 'Connectome'), ('gene', 'Gene Expression'), ('activity', 'Activity Maps')], max_length=256, null=True),
        ),
    ]
