# Generated by Django 3.1.3 on 2021-03-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0031_post_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.CharField(help_text='Unique URL pattern that is used for access @ BASEURL/post/url/', max_length=128, null=True, unique=True),
        ),
    ]
