# Generated by Django 3.1.3 on 2021-03-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0032_auto_20210314_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.CharField(help_text='Unique URL pattern that is used for access @ BASEURL/post/url/', max_length=128, unique=True),
        ),
    ]
